#!/usr/bin/env bash
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"

staged_go_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true)

if [ -z "$staged_go_files" ]; then
  exit 0
fi

echo "Running gofmt..."
echo "$staged_go_files" | xargs gofmt -l -w
echo "$staged_go_files" | xargs git add

echo "Running golangci-lint..."
bash "$root/scripts/lint-go.sh"
