# syntax=docker/dockerfile:1

ARG NODE_VERSION=22.14.0

FROM node:${NODE_VERSION}-alpine3.21
WORKDIR /app
RUN npm install -g prisma@6.5.0
COPY packages/database/prisma ./prisma
ENV NODE_ENV=production
ENTRYPOINT ["prisma", "migrate", "deploy", "--schema=/app/prisma/schema.prisma"]
