package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/novacommerce/identity-service/internal/application/usecase"
	apperrors "github.com/novacommerce/pkg/errors"
)

// OAuthHandler serves OAuth2 login and callback endpoints.
type OAuthHandler struct {
	oauthUseCase usecase.OAuthUseCase
}

// NewOAuthHandler creates an OAuthHandler.
func NewOAuthHandler(oauthUseCase usecase.OAuthUseCase) *OAuthHandler {
	return &OAuthHandler{oauthUseCase: oauthUseCase}
}

// Redirect handles GET /auth/oauth/:provider
//
// Generates a CSRF state, stores it in Redis, and issues a 302 redirect to
// the provider's consent page. An optional `redirect_url` query parameter
// may be supplied by the frontend for use after authentication completes.
func (h *OAuthHandler) Redirect(c *gin.Context) {
	provider := c.Param("provider")
	redirectURL := c.Query("redirect_url")

	authURL, err := h.oauthUseCase.GetAuthURL(c.Request.Context(), provider, redirectURL)
	if err != nil {
		respondError(c, err)
		return
	}

	c.Redirect(http.StatusFound, authURL)
}

// Callback handles GET /auth/oauth/:provider/callback
//
// Validates the CSRF state, exchanges the authorisation code for tokens,
// resolves (or auto-creates) the user, and returns a token pair.
//
// Query parameters (supplied by the OAuth provider):
//   - code  – authorisation code
//   - state – CSRF token originally generated by /auth/oauth/:provider
//   - error – set by the provider when the user denies access
func (h *OAuthHandler) Callback(c *gin.Context) {
	// Surface provider-side errors (e.g. user denied access) immediately.
	if providerErr := c.Query("error"); providerErr != "" {
		description := c.Query("error_description")
		if description == "" {
			description = providerErr
		}
		respondError(c, apperrors.NewUnauthorized("oauth provider error: "+description))
		return
	}

	provider := c.Param("provider")
	code := c.Query("code")
	state := c.Query("state")

	if code == "" {
		respondError(c, apperrors.NewBadRequest("missing authorization code"))
		return
	}
	if state == "" {
		respondError(c, apperrors.NewBadRequest("missing state parameter"))
		return
	}

	output, err := h.oauthUseCase.HandleCallback(c.Request.Context(), provider, code, state)
	if err != nil {
		respondError(c, err)
		return
	}

	respondSuccess(c, http.StatusOK, output)
}
