export const DEFAULT_PRODUCT_SEARCH_PAGE = 1;
export const DEFAULT_PRODUCT_SEARCH_PAGE_SIZE = 20;
export const MAX_PRODUCT_SEARCH_PAGE_SIZE = 100;
export const MAX_PRODUCT_SEARCH_QUERY_LENGTH = 200;
export const MAX_PRODUCT_SEARCH_RESULT_WINDOW = 10_000;
